# Generated by Django 3.0.8 on 2020-08-07 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe24',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extract_day', models.CharField(default=datetime.datetime(2020, 8, 7, 17, 47, 50, 172255), max_length=10, verbose_name='출고일자')),
                ('order_num', models.TextField(verbose_name='주문번호')),
                ('truck', models.TextField(blank=True, verbose_name='트럭출고')),
                ('bj_code', models.TextField(default='0001', verbose_name='발주처코드')),
                ('bj_name', models.TextField(blank=True, verbose_name='발주처명')),
                ('bs', models.TextField(default='0000', verbose_name='배송(주문)')),
                ('bs_name', models.TextField(blank=True, verbose_name='배송(주문)처명')),
                ('receiver', models.TextField(verbose_name='수령자')),
                ('bs_address', models.TextField(verbose_name='배송처')),
                ('post_id', models.TextField(verbose_name='우편번호')),
                ('phone', models.TextField(verbose_name='대표연락처')),
                ('phone2', models.TextField(verbose_name='연락처2')),
                ('bs_yogoo', models.TextField(blank=True, verbose_name='배송요구사항')),
                ('dp_code', models.TextField(blank=True, verbose_name='대표코드')),
                ('product_code', models.TextField(blank=True, verbose_name='제품코드')),
                ('product', models.TextField(blank=True, verbose_name='제품')),
                ('amount', models.TextField(verbose_name='수량')),
                ('is_normal', models.TextField(blank=True, verbose_name='정상여부')),
                ('memo1', models.TextField(blank=True, verbose_name='메모1')),
                ('memo2', models.TextField(blank=True, verbose_name='메모2')),
                ('memo3', models.TextField(blank=True, verbose_name='메모3')),
            ],
        ),
    ]
