# Generated by Django 3.0.8 on 2020-10-26 06:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryExcel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateField(auto_now_add=True, verbose_name='업로드 날짜')),
                ('excel_file', models.FileField(upload_to='', verbose_name='송장 엑셀')),
                ('source', models.CharField(choices=[('C', 'CAFE 24'), ('N', '네이버 스토어팜'), ('E', '기타')], max_length=100, verbose_name='송장 종류')),
            ],
            options={
                'verbose_name': '송장 엑셀',
                'verbose_name_plural': '송장 엑셀들',
            },
        ),
        migrations.AlterModelOptions(
            name='cafe24',
            options={'verbose_name': '카페24', 'verbose_name_plural': '카페24'},
        ),
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 26, 15, 16, 54, 516299), max_length=10, verbose_name='출고일자'),
        ),
    ]
