# Generated by Django 3.0.8 on 2020-10-26 07:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0003_auto_20201026_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 26, 16, 19, 15, 545230), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='source',
            field=models.CharField(choices=[('CAFE 24', 'CAFE 24'), ('네이버 스토어팜', '네이버 스토어팜'), ('기타', '기타')], max_length=100, verbose_name='송장 종류'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 26, 16, 19, 15, 545230), verbose_name='업로드 날짜'),
        ),
    ]
