# Generated by Django 3.0.8 on 2020-10-28 04:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0004_auto_20201026_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cafe24Temp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cf_1', models.TextField(blank=True, null=True, verbose_name='주문번호')),
                ('cf_2', models.TextField(blank=True, null=True, verbose_name='품목번호')),
                ('cf_3', models.TextField(blank=True, null=True, verbose_name='품목별 주문번호')),
                ('cf_4', models.TextField(blank=True, null=True, verbose_name='수령인')),
                ('cf_5', models.TextField(blank=True, null=True, verbose_name='수령인 주소(전체)')),
                ('cf_6', models.TextField(blank=True, null=True, verbose_name='수령인 우편번호')),
                ('cf_7', models.TextField(blank=True, null=True, verbose_name='수령인 휴대전화')),
                ('cf_8', models.TextField(blank=True, null=True, verbose_name='수령인 전화번호')),
                ('cf_9', models.TextField(blank=True, null=True, verbose_name='배송메시지')),
                ('cf_10', models.TextField(blank=True, null=True, verbose_name='주문상품명(옵션포함)')),
                ('cf_11', models.TextField(blank=True, null=True, verbose_name='자체품목코드')),
                ('cf_12', models.TextField(blank=True, null=True, verbose_name='수량')),
                ('cf_13', models.TextField(blank=True, null=True, verbose_name='상품구매금액(KRW)')),
                ('cf_14', models.TextField(blank=True, null=True, verbose_name='상품별 추가할인금액')),
            ],
        ),
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 13, 28, 27, 810876), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 13, 28, 27, 810876), verbose_name='업로드 날짜'),
        ),
    ]
