# Generated by Django 3.0.8 on 2020-10-28 05:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0006_auto_20201028_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe24temp',
            name='product_name',
            field=models.TextField(blank=True, null=True, verbose_name='주문상품명(옵션포함)'),
        ),
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 14, 25, 1, 198416), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='cafe24temp',
            name='product_num',
            field=models.TextField(blank=True, null=True, verbose_name='품목번호'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 14, 25, 1, 198416), verbose_name='업로드 날짜'),
        ),
    ]
