# Generated by Django 3.0.8 on 2020-10-28 05:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0007_auto_20201028_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe24temp',
            name='made_by_source',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='drmamma.DeliveryExcel', verbose_name='연관 엑셀'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 14, 36, 43, 351664), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 14, 36, 43, 351664), verbose_name='업로드 날짜'),
        ),
    ]
