# Generated by Django 3.0.8 on 2020-10-28 05:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0008_auto_20201028_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 14, 37, 6, 643240), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='cafe24temp',
            name='made_by_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drmamma.DeliveryExcel', verbose_name='연관 엑셀'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 14, 37, 6, 643240), verbose_name='업로드 날짜'),
        ),
    ]
