# Generated by Django 3.0.8 on 2020-10-28 08:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0009_auto_20201028_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 17, 13, 40, 387221), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 17, 13, 40, 388218), verbose_name='업로드 날짜'),
        ),
    ]
