# Generated by Django 3.0.8 on 2020-10-28 08:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0010_auto_20201028_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_range', models.CharField(choices=[('3만원~', '3만원~'), ('3만원~6만원', '3만원~6만원'), ('6만원~10만원', '6만원~10만원'), ('10만원~', '10만원~')], max_length=100, verbose_name='가격 범위')),
                ('sample_dog_name', models.CharField(max_length=100, verbose_name='강아지 샘플 이름')),
                ('sample_dog_code', models.CharField(max_length=100, verbose_name='강아지 샘플 코드')),
                ('sample_cat_name', models.CharField(max_length=100, verbose_name='고양이 샘플 이름')),
                ('sample_cat_code', models.CharField(max_length=100, verbose_name='고양이 샘플 코드')),
            ],
        ),
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 17, 58, 43, 472509), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 17, 58, 43, 473506), verbose_name='업로드 날짜'),
        ),
    ]
