# Generated by Django 3.0.8 on 2020-10-28 08:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0011_auto_20201028_1758'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'verbose_name': '샘플', 'verbose_name_plural': '샘플'},
        ),
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 17, 59, 21, 191934), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 17, 59, 21, 192931), verbose_name='업로드 날짜'),
        ),
    ]
