# Generated by Django 3.0.8 on 2020-10-28 09:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0012_auto_20201028_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe24',
            name='extract_day',
            field=models.CharField(default=datetime.datetime(2020, 10, 28, 18, 6, 36, 911195), max_length=10, verbose_name='출고일자'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 28, 18, 6, 36, 912191), verbose_name='업로드 날짜'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_range',
            field=models.CharField(choices=[('~3만원', '~3만원'), ('3만원~6만원', '3만원~6만원'), ('6만원~10만원', '6만원~10만원'), ('10만원~', '10만원~')], max_length=100, verbose_name='가격 범위'),
        ),
    ]
