# Generated by Django 3.0.8 on 2020-10-29 04:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0014_auto_20201029_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverFarmTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.TextField(blank=True, null=True, verbose_name='발주처 코드')),
                ('order_pk', models.TextField(blank=True, null=True, verbose_name='주문번호')),
                ('product_num', models.TextField(blank=True, null=True, verbose_name='품목번호')),
                ('product_order_num', models.TextField(blank=True, null=True, verbose_name='품목별 주문번호')),
                ('receiver', models.TextField(blank=True, null=True, verbose_name='수령인')),
                ('address', models.TextField(blank=True, null=True, verbose_name='수령인 주소(전체)')),
                ('post_num', models.TextField(blank=True, null=True, verbose_name='수령인 우편번호')),
                ('phone_num', models.TextField(blank=True, null=True, verbose_name='수령인 휴대전화')),
                ('phone_num2', models.TextField(blank=True, null=True, verbose_name='수령인 전화번호')),
                ('message', models.TextField(blank=True, null=True, verbose_name='배송메시지')),
                ('product_name', models.TextField(blank=True, null=True, verbose_name='주문상품명(옵션포함)')),
                ('product_code', models.TextField(blank=True, null=True, verbose_name='자체품목코드')),
                ('amount', models.TextField(blank=True, null=True, verbose_name='수량')),
                ('price', models.TextField(blank=True, null=True, verbose_name='상품구매금액(KRW)')),
                ('discount', models.TextField(blank=True, null=True, verbose_name='상품별 추가할인금액')),
                ('total_price', models.TextField(blank=True, null=True, verbose_name='총 주문 금액')),
            ],
            options={
                'verbose_name': '네이버 스토어팜',
                'verbose_name_plural': '네이버 스토어팜',
            },
        ),
        migrations.DeleteModel(
            name='Cafe24',
        ),
        migrations.AlterModelOptions(
            name='cafe24temp',
            options={'verbose_name': 'Cafe24', 'verbose_name_plural': 'Cafe24'},
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 29, 13, 14, 48, 524036), verbose_name='업로드 날짜'),
        ),
        migrations.AddField(
            model_name='naverfarmtemp',
            name='made_by_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drmamma.DeliveryExcel', verbose_name='연관 엑셀'),
        ),
    ]
