# Generated by Django 3.0.8 on 2020-10-29 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0015_auto_20201029_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe24temp',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='cafe24temp',
            name='price',
        ),
        migrations.RemoveField(
            model_name='cafe24temp',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='cafe24temp',
            name='product_num',
        ),
        migrations.RemoveField(
            model_name='cafe24temp',
            name='product_order_num',
        ),
        migrations.RemoveField(
            model_name='naverfarmtemp',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='naverfarmtemp',
            name='price',
        ),
        migrations.RemoveField(
            model_name='naverfarmtemp',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='naverfarmtemp',
            name='product_num',
        ),
        migrations.RemoveField(
            model_name='naverfarmtemp',
            name='product_order_num',
        ),
        migrations.AddField(
            model_name='cafe24temp',
            name='discount_coupon',
            field=models.TextField(blank=True, null=True, verbose_name='쿠폰 할인 금액'),
        ),
        migrations.AddField(
            model_name='cafe24temp',
            name='discount_product',
            field=models.TextField(blank=True, null=True, verbose_name='상품별 추가할인금액'),
        ),
        migrations.AddField(
            model_name='cafe24temp',
            name='standard_for_gift',
            field=models.TextField(blank=True, null=True, verbose_name='사은품 기준 금액'),
        ),
        migrations.AddField(
            model_name='cafe24temp',
            name='used_reserves',
            field=models.TextField(blank=True, null=True, verbose_name='사용한 적립금액'),
        ),
        migrations.AddField(
            model_name='naverfarmtemp',
            name='discount_coupon',
            field=models.TextField(blank=True, null=True, verbose_name='쿠폰 할인 금액'),
        ),
        migrations.AddField(
            model_name='naverfarmtemp',
            name='discount_product',
            field=models.TextField(blank=True, null=True, verbose_name='상품별 추가할인금액'),
        ),
        migrations.AddField(
            model_name='naverfarmtemp',
            name='standard_for_gift',
            field=models.TextField(blank=True, null=True, verbose_name='사은품 기준 금액'),
        ),
        migrations.AddField(
            model_name='naverfarmtemp',
            name='used_reserves',
            field=models.TextField(blank=True, null=True, verbose_name='사용한 적립금액'),
        ),
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=datetime.datetime(2020, 10, 29, 14, 12, 30, 128415), verbose_name='업로드 날짜'),
        ),
    ]
