# Generated by Django 3.0.8 on 2020-10-29 05:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0016_auto_20201029_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryexcel',
            name='uploaded_at',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='업로드 날짜'),
        ),
    ]
