# Generated by Django 3.0.8 on 2020-10-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0017_auto_20201029_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cafe24temp',
            name='standard_for_gift',
        ),
    ]
