# Generated by Django 3.0.8 on 2020-11-03 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0019_auto_20201029_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='ETCTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_code', models.TextField(blank=True, null=True, verbose_name='발주처 코드')),
                ('order_pk', models.TextField(blank=True, null=True, verbose_name='주문번호')),
                ('receiver', models.TextField(blank=True, null=True, verbose_name='수령인')),
                ('address', models.TextField(blank=True, null=True, verbose_name='수령인 주소(전체)')),
                ('post_num', models.TextField(blank=True, null=True, verbose_name='수령인 우편번호')),
                ('phone_num', models.TextField(blank=True, null=True, verbose_name='수령인 휴대전화')),
                ('phone_num2', models.TextField(blank=True, null=True, verbose_name='수령인 전화번호')),
                ('message', models.TextField(blank=True, null=True, verbose_name='배송메시지')),
                ('product_code', models.TextField(blank=True, null=True, verbose_name='자체품목코드')),
                ('amount', models.TextField(blank=True, null=True, verbose_name='수량')),
                ('total_price', models.TextField(blank=True, null=True, verbose_name='총 주문 금액')),
                ('order_price', models.TextField(blank=True, null=True, verbose_name='배송비 합계')),
                ('made_by_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drmamma.DeliveryExcel', verbose_name='연관 엑셀')),
            ],
            options={
                'verbose_name': '네이버 스토어팜',
                'verbose_name_plural': '네이버 스토어팜',
            },
        ),
    ]
