# Generated by Django 3.0.8 on 2020-11-05 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0020_etctemp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PRODUCT_CODE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, verbose_name='상품 코드')),
                ('name', models.CharField(max_length=200, verbose_name='상품 명')),
            ],
            options={
                'verbose_name': '상품 코드 & 상품명',
                'verbose_name_plural': '상품 코드 & 상품명',
            },
        ),
        migrations.AlterModelOptions(
            name='etctemp',
            options={'verbose_name': '기타 송장', 'verbose_name_plural': '기타 송장'},
        ),
    ]
