# Generated by Django 3.0.8 on 2021-03-23 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0021_auto_20201105_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='max_range',
            field=models.PositiveIntegerField(null=True, verbose_name='[]원 전까지'),
        ),
        migrations.AddField(
            model_name='sample',
            name='min_range',
            field=models.PositiveIntegerField(null=True, verbose_name='[]원 부터'),
        ),
    ]
