# Generated by Django 3.0.8 on 2021-03-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drmamma', '0023_auto_20210323_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_range',
            field=models.CharField(max_length=100, verbose_name='가격 범위'),
        ),
    ]
